### Essential NumPy and Pandas Functions for Data Analysis

Let's look at practical code snippets that demonstrate the most useful NumPy and pandas methods for data analysis in Python. You can use these in a Jupyter notebook for experimentation and workflow mastery.

#### NumPy Basics for Data Analysis
Import NumPy:

In [2]:
import numpy as np

1. Creating Arrays

In [3]:
arr = np.array([1, 2, 3, 4])            # 1D array
matrix = np.array([[1, 2], [3, 4]])     # 2D array
zeros = np.zeros((2, 3))                # 2x3 array of zeros
ones = np.ones((2, 3))                  # 2x3 array of ones
rnd = np.random.rand(2, 3)              # 2x3 array of random floats

2. Array Shape, Reshape, Flatten

In [4]:
print(arr.shape)                # (4,)
reshaped = matrix.reshape((4, 1))   # Reshape to 4 rows, 1 column
flat = matrix.ravel()               # Flatten to 1D array

(4,)


3. Indexing and Slicing

In [5]:
print(matrix[0, 1])    # element at first row, second column
print(arr[1:3])        # slice elements 1 to 2

2
[2 3]


4. Basic Math Operations

In [6]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print(a + b)           # [11 22 33]
print(a - b)           # [ 9 18 27]
print(a * b)           # [10 40 90]
print(a / b)           # [10. 10. 10.]


[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


5. Aggregation and Stats

In [7]:
np.sum(arr)                 # 10
np.mean(arr)                # 2.5
np.std(arr)                 # Standard deviation
np.min(arr), np.max(arr)    # Min and max values

(np.int64(1), np.int64(4))

6. Dot Product, Matrix Ops

In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot = np.dot(a, b)          # 1*4 + 2*5 + 3*6 = 32
mat = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
matprod = np.matmul(mat, mat2) # Matrix multiplication

7. Logical and Filtering

In [9]:
arr[arr > 2]                # Returns [3, 4]
np.where(arr > 2)           # Indices where condition is true

(array([2, 3]),)

8. Random Sampling

In [10]:
np.random.randint(0, 100, size=5) # 5 random ints 0-99
np.random.choice([0, 1], size=10) # 10 random 0s or 1s

array([1, 0, 0, 1, 1, 0, 1, 1, 0, 1])

#### Pandas Basics for Data Analysis
Import pandas:

In [11]:
import pandas as pd

1. Creating DataFrames

In [12]:
data = {'A': [1, 2, 3], 'B': [4, 5, 6]}
df = pd.DataFrame(data) # Create DataFrame

2. Inspecting Data

In [13]:
df.head()                # First 5 rows
df.tail(3)                # Last 3 rows
df.info()                 # DataFrame info + datatypes
df.describe()             # Summary statistics

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
dtypes: int64(2)
memory usage: 180.0 bytes


A    B
count  3.0  3.0
mean   2.0  5.0
std    1.0  1.0
min    1.0  4.0
25%    1.5  4.5
50%    2.0  5.0
75%    2.5  5.5
max    3.0  6.0

3. Selecting Data

In [14]:
df['A']                   # Get column A
df.loc[0]                 # Row by label (index 0)
df.iloc[1:3]              # Rows 1-2 by position
df[df['A'] > 1]           # Filter rows where A > 1

A  B
1  2  5
2  3  6

4. Adding/Dropping Columns

In [15]:
df['C'] = df['A'] + df['B']     # Add new column
new_df = df.drop('B', axis=1)   # Drop column B

5. Missing Values & Types

In [16]:
df.isnull().sum()               # Missing values per column
df.fillna(0)                    # Replace NaNs with 0
df['A'] = df['A'].astype(float) # Change column type

6. Grouping and Aggregation

In [17]:
grouped = df.groupby('A').sum()   # Sum columns, grouped by values in A
df['A'].value_counts()            # Count unique values in A

A
1.0    1
2.0    1
3.0    1
Name: count, dtype: int64

7. Sorting

In [18]:
df.sort_values('B', ascending=False)  # Sort by column B

A  B  C
2  3.0  6  9
1  2.0  5  7
0  1.0  4  5

8. Reading/Writing Files

In [19]:
df.to_csv('mydata.csv') # Save to CSV
df = pd.read_csv('mydata.csv') # Load from CSV
df.head()

Unnamed: 0    A  B  C
0           0  1.0  4  5
1           1  2.0  5  7
2           2  3.0  6  9

9. Apply/Map Functions

In [20]:
df['A_squared'] = df['A'].apply(lambda x: x**2) # Apply to column
df['B_label'] = df['B'].map({4: 'Low', 5: 'Med', 6: 'High'}) # Map values
df.sample(3)

Unnamed: 0    A  B  C  A_squared B_label
2           2  3.0  6  9        9.0    High
1           1  2.0  5  7        4.0     Med
0           0  1.0  4  5        1.0     Low

### Task:

- Generated a Synthetic Dataset with columns of `age`, `salary`, `department`, `years_experience`, and `is_manager`.

In [21]:
np.random.seed(42) # For reproducibility
n_samples = 100 # Number of samples

data = {
    'age': np.random.randint(18, 60, size=n_samples),
    'salary': np.random.randint(30000, 120000, size=n_samples),
    'department': np.random.choice(['IT', 'HR', 'Finance', 'Marketing'], size=n_samples),
    'years_experience': np.round(np.random.normal(5, 2, size=n_samples), 1),
    'is_manager': np.random.choice([0, 1], size=n_samples)
}
df = pd.DataFrame(data)

Q1. View data structure

In [22]:
df

age  salary department  years_experience  is_manager
0    56   38392         IT              -0.8           0
1    46   60535  Marketing               3.4           1
2    32  108603         HR               5.0           1
3    25   82256         HR               4.2           1
4    38  119135         HR               4.1           1
..  ...     ...        ...               ...         ...
95   59   82662         IT               4.0           0
96   56   42688         HR               4.4           1
97   58   55342  Marketing               6.0           0
98   45   67157         HR              11.4           0
99   24   97863         HR               5.2           1

[100 rows x 5 columns]

Q2. Get DataFrame Info and Summary Stats

In [23]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   age               100 non-null    int32  
 1   salary            100 non-null    int32  
 2   department        100 non-null    object 
 3   years_experience  100 non-null    float64
 4   is_manager        100 non-null    int64  
dtypes: float64(1), int32(2), int64(1), object(1)
memory usage: 3.3+ KB


age         salary  years_experience  is_manager
count  100.000000     100.000000        100.000000  100.000000
mean    37.910000   77809.160000          4.823000    0.470000
std     12.219454   26058.643576          2.237822    0.501614
min     18.000000   30206.000000         -0.800000    0.000000
25%     26.750000   55141.000000          3.475000    0.000000
50%     38.000000   80932.000000          4.700000    0.000000
75%     46.250000   98107.250000          6.000000    1.000000
max     59.000000  119474.000000         11.400000    1.000000

Q3. Do Simple Numpy Operations

In [24]:
print(df['age'].mean())          # Average age
print(df['salary'].max())        # Max salary
print(df['salary'].min())        # Min salary
print(df['department'].value_counts()) # Count per department
print(df['years_experience'].std()) # Std dev of experience


37.91
119474
30206
department
Marketing    36
Finance      24
IT           21
HR           19
Name: count, dtype: int64
2.237822489597755


Q4. Filtering and Indexing Rows

In [31]:
print(df[df['salary'] > 110000]) # Employees with salary > 110k
print(df[(df["is_manager"]==1) & (df["department"]=="IT") & (df["age"] > 30)]) # Count

    age  salary department  years_experience  is_manager       location
4    38  119135         HR               4.1           1       New York
8    28  114651  Marketing               5.8           1         Austin
17   41  112948  Marketing               6.7           1  San Francisco
20   19  117054  Marketing               6.7           0         Austin
21   38  117897    Finance               5.8           0        Chicago
26   44  117939  Marketing               1.4           0       New York
28   45  110356    Finance               5.7           1         Austin
35   26  111734         HR               3.8           0        Chicago
76   42  113211         HR               8.6           0  San Francisco
79   32  119474  Marketing               4.3           1         Austin
82   24  115616         IT               9.3           1  San Francisco
89   34  117092    Finance               4.5           0         Austin
92   52  117455         IT               3.9           0        

Q5. Adding a Column

In [29]:
df["location"]= np.random.choice(['New York', 'San Francisco', 'Chicago', 'Austin'], size=n_samples)
df.head()

age  salary department  years_experience  is_manager       location
0   56   38392         IT              -0.8           0         Austin
1   46   60535  Marketing               3.4           1         Austin
2   32  108603         HR               5.0           1       New York
3   25   82256         HR               4.2           1  San Francisco
4   38  119135         HR               4.1           1       New York

Q6. Grouping and Aggregation

In [28]:
print(df.groupby('department')['salary'].mean()) # Avg salary by department
print(df.groupby('is_manager')['age'].mean()) # Avg age by manager status

department
Finance      83124.708333
HR           73523.052632
IT           75825.476190
Marketing    77684.722222
Name: salary, dtype: float64
is_manager
0    38.886792
1    36.808511
Name: age, dtype: float64
