### Essential NumPy and Pandas Functions for Data Analysis

Let's look at practical code snippets that demonstrate the most useful NumPy and pandas methods for data analysis in Python. You can use these in a Jupyter notebook for experimentation and workflow mastery.

#### NumPy Basics for Data Analysis
Import NumPy:

In [1]:
import numpy as np

1. Creating Arrays

In [115]:
#arr = np.array([1, 2, 3, 4])            # 1D array
#matrix = np.array([[1, 2], [3, 4]])     # 2D array
#zeros = np.zeros((2, 3))                # 2x3 array of zeros
#ones = np.ones((2, 3))                  # 2x3 array of ones
rnd = np.random.rand(2, 4)              # 2x3 array of random floats
rnd

array([[0.86859913, 0.22359584, 0.96322254, 0.01215447],
       [0.96987883, 0.04315991, 0.89114311, 0.52770111]])

2. Array Shape, Reshape, Flatten

In [3]:
print(arr.shape)                # (4,)
reshaped = matrix.reshape((4, 1))   # Reshape to 4 rows, 1 column
flat = matrix.ravel()               # Flatten to 1D array

(4,)


3. Indexing and Slicing

In [4]:
print(matrix[0, 1])    # element at first row, second column
print(arr[1:3])        # slice elements 1 to 2

2
[2 3]


4. Basic Math Operations

In [5]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print(a + b)           # [11 22 33]
print(a - b)           # [ 9 18 27]
print(a * b)           # [10 40 90]
print(a / b)           # [10. 10. 10.]


[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


5. Aggregation and Stats

In [6]:
np.sum(arr)                 # 10
np.mean(arr)                # 2.5
np.std(arr)                 # Standard deviation
np.min(arr), np.max(arr)    # Min and max values

(np.int64(1), np.int64(4))

6. Dot Product, Matrix Ops

In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot = np.dot(a, b)          # 1*4 + 2*5 + 3*6 = 32
mat = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
matprod = np.matmul(mat, mat2) # Matrix multiplication

7. Logical and Filtering

In [24]:
arr[arr > 2]                # Returns [3, 4]
np.where(arr > 2)           # Indices where condition is true

(array([2, 3]),)

8. Random Sampling

In [26]:
np.random.randint(0, 100, size=5) # 5 random ints 0-99
np.random.choice([0, 1], size=10) # 10 random 0s or 1s

array([0, 0, 1, 0, 0, 1, 1, 0, 1, 1])

#### Pandas Basics for Data Analysis
Import pandas:

In [10]:
import pandas as pd

1. Creating DataFrames

In [80]:
data = {'A': [1, 2, 3], 'B': [4, 5, 6]}
df = pd.DataFrame(data) # Create DataFrame

2. Inspecting Data

In [82]:
df.head()                # First 5 rows
df.tail(3)                # Last 3 rows
df.info()                 # DataFrame info + datatypes
df.describe()             # Summary statistics

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
dtypes: int64(2)
memory usage: 180.0 bytes


A    B
count  3.0  3.0
mean   2.0  5.0
std    1.0  1.0
min    1.0  4.0
25%    1.5  4.5
50%    2.0  5.0
75%    2.5  5.5
max    3.0  6.0

3. Selecting Data

In [83]:
df['A']                   # Get column A
df.loc[0]                 # Row by label (index 0)
df.iloc[1:2]              # Rows 1-2 by position
df[df['A'] > 1]           # Filter rows where A > 1

A  B
1  2  5
2  3  6

4. Adding/Dropping Columns

In [84]:
df['C'] = df['A'] + df['B']     # Add new column
new_df = df.drop('B', axis=1)   # Drop column B

5. Missing Values & Types

In [85]:
df.isnull().sum()             # Missing values per column
df.fillna(0)                    # Replace NaNs with 0
df['A'] = df['A'].astype(float) # Change column type

6. Grouping and Aggregation

In [86]:
grouped = df.groupby('A').sum()   # Sum columns, grouped by values in A
df['A'].value_counts()            # Count unique values in A

A
1.0    1
2.0    1
3.0    1
Name: count, dtype: int64

7. Sorting

In [87]:
df.sort_values('B', ascending=False)  # Sort by column B

A  B  C
2  3.0  6  9
1  2.0  5  7
0  1.0  4  5

8. Reading/Writing Files

In [88]:
df.to_csv('mydata.csv') # Save to CSV
df = pd.read_csv('mydata.csv') # Load from CSV
df.head()

Unnamed: 0    A  B  C
0           0  1.0  4  5
1           1  2.0  5  7
2           2  3.0  6  9

9. Apply/Map Functions

In [99]:
df['A_squared'] = df['A'].apply(lambda x: x**2) # Apply to column
df['B_label'] = df['B'].map({4: 'Low', 5: 'Med', 6: 'High'}) # Map values
df.sample(2)

Unnamed: 0    A  B  C  A_squared B_label
0           0  1.0  4  5        1.0     Low
2           2  3.0  6  9        9.0    High

### Task:

- Generated a Synthetic Dataset with columns of `age`, `salary`, `department`, `years_experience`, and `is_manager`.

In [167]:
np.random.seed(42) # For reproducibility
n_samples = 100 # Number of samples

data = {
    'age': np.random.randint(18, 60, size=n_samples),
    'salary': np.random.randint(30000, 120000, size=n_samples),
    'department': np.random.choice(['IT', 'HR', 'Finance', 'Marketing'], size=n_samples),
    'years_experience': np.round(np.random.normal(5, 2, size=n_samples), 2), #5=mean,2=standard deviation
    'is_manager': np.random.choice([0, 1], size=n_samples)
}
df = pd.DataFrame(data)

Q1. View data structure

In [168]:
df.head()

age  salary department  years_experience  is_manager
0   56   38392         IT             -0.76           0
1   46   60535  Marketing              3.39           1
2   32  108603         HR              4.99           1
3   25   82256         HR              4.23           1
4   38  119135         HR              4.07           1

Q2. Get DataFrame Info and Summary Stats

In [169]:
df.info()
df.describe()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   age               100 non-null    int64  
 1   salary            100 non-null    int64  
 2   department        100 non-null    object 
 3   years_experience  100 non-null    float64
 4   is_manager        100 non-null    int64  
dtypes: float64(1), int64(3), object(1)
memory usage: 4.0+ KB


age         salary  years_experience  is_manager
count  100.000000     100.000000        100.000000  100.000000
mean    37.910000   77809.160000          4.823800    0.470000
std     12.219454   26058.643576          2.235851    0.501614
min     18.000000   30206.000000         -0.760000    0.000000
25%     26.750000   55141.000000          3.450000    0.000000
50%     38.000000   80932.000000          4.730000    0.000000
75%     46.250000   98107.250000          6.020000    1.000000
max     59.000000  119474.000000         11.370000    1.000000

Q3. Do Simple Numpy Operations

In [170]:
# Increase salary by 10%
df['Salary'] = np.round(df['salary'] * 1.1, 2)

# Add 2 years to experience
df['Experience'] = np.round(df['years_experience'] + 2, 1)

# Example: total years (age + experience)
df['Total_Years'] = df['age'] + df['years_experience']
df.head()


age  salary department  years_experience  is_manager    Salary  Experience  \
0   56   38392         IT             -0.76           0   42231.2         1.2   
1   46   60535  Marketing              3.39           1   66588.5         5.4   
2   32  108603         HR              4.99           1  119463.3         7.0   
3   25   82256         HR              4.23           1   90481.6         6.2   
4   38  119135         HR              4.07           1  131048.5         6.1   

   Total_Years  
0        55.24  
1        49.39  
2        36.99  
3        29.23  
4        42.07

Q4. Filtering and Indexing Rows

In [171]:
df['Bonus'] = df['salary'].apply(lambda x: x/2) # Apply to column
df['ismanager'] = df['is_manager'].map({0: 'No', 1: 'Yes'})
df.iloc[:6]


age  salary department  years_experience  is_manager    Salary  Experience  \
0   56   38392         IT             -0.76           0   42231.2         1.2   
1   46   60535  Marketing              3.39           1   66588.5         5.4   
2   32  108603         HR              4.99           1  119463.3         7.0   
3   25   82256         HR              4.23           1   90481.6         6.2   
4   38  119135         HR              4.07           1  131048.5         6.1   
5   56   65222    Finance              2.78           0   71744.2         4.8   

   Total_Years    Bonus ismanager  
0        55.24  19196.0        No  
1        49.39  30267.5       Yes  
2        36.99  54301.5       Yes  
3        29.23  41128.0       Yes  
4        42.07  59567.5       Yes  
5        58.78  32611.0        No

Q5. Adding a Column

In [180]:
df['Total_salary'] = df['Bonus'] + df['salary']     # Add new column
df['Total_salary'].iloc[:5]

0     57588.0
1     90802.5
2    162904.5
3    123384.0
4    178702.5
Name: Total_salary, dtype: float64

Q6. Grouping and Aggregation

In [178]:
dff=df[['salary','years_experience','is_manager']].groupby('is_manager').mean()
dff

salary  years_experience
is_manager                                
0           76500.867925          5.254528
1           79284.468085          4.338085

In [179]:
df['is_manager'].value_counts()            # Count unique values in is_manager

is_manager
0    53
1    47
Name: count, dtype: int64